magentix_pickup_checkout_pickup_list:
    path: /pickup-list/{method}/{postcode}/{countryCode}
    defaults:
        _controller: MagentixPickupPlugin:Pickup:list
        postcode: ~
        countryCode: ~

magentix_pickup_ajax_pickup_list:
    path: /pickup-list
    methods: [GET]
    defaults:
        _controller: magentix_pickup_checkout_pickup_list
