magentix_sylius_pickup_checkout_pickup_list:
    path: /pickup-list/{method}
    defaults:
        _controller: MagentixSyliusPickupPlugin:Pickup:list

magentix_sylius_pickup_ajax_pickup_list:
    path: /pickup-list
    methods: [GET]
    defaults:
        _controller: magentix_sylius_pickup_checkout_pickup_list
