magentix_pickup_checkout_pickup_list:
    path: /pickup-list/{method}
    defaults:
        _controller: MagentixPickupPlugin:Pickup:list

magentix_pickup_ajax_pickup_list:
    path: /pickup-list
    methods: [GET]
    defaults:
        _controller: magentix_pickup_checkout_pickup_list
