services:
    sylius.customer_order_addresses_saver:
        class: MagentixSyliusPickupPlugin\Component\Core\Customer\CustomerOrderAddressesSaver
        public: true
        arguments:
            - "@sylius.customer_unique_address_adder"