services:
    MagentixSyliusPickupPlugin\Controller\PickupController:
        public: true
        arguments:
            - "@sylius.registry.shipping_calculator"
            - "@sylius.repository.country"