imports:
    - { resource: "@MagentixPickupPlugin/Resources/config/services.yml" }

sylius_shipping:
    resources:
        shipment:
            classes:
                model: MagentixPickupPlugin\Entity\Shipment
