imports:
    - { resource: "@MagentixSyliusPickupPlugin/Resources/config/services.yml" }

sylius_shipping:
    resources:
        shipment:
            classes:
                model: Magentix\SyliusPickupPlugin\Entity\Shipment
