services:
    app.block_event_listener.shop.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@MagentixPickupPlugin/checkout/SelectShipping/pickup.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.javascripts, method: onBlockEvent }

    MagentixPickupPlugin\Controller\PickupController:
        public: true
        arguments:
            - "@sylius.registry.shipping_calculator"

    magentix_pickup_plugin.order.initialize_complete:
        class: MagentixPickupPlugin\EventListener\OrderInitializeCompleteListener
        arguments:
            - "@sylius.registry.shipping_calculator"
            - "@sylius.repository.shipping_method"
            - "@sylius.repository.shipment"
        tags:
            - { name: kernel.event_listener, event: sylius.order.initialize_complete, method: updateShippingAddress }

    magentix_pickup_plugin.order.pre_complete:
        class: MagentixPickupPlugin\EventListener\OrderPreCompleteListener
        arguments:
            - "@sylius.registry.shipping_calculator"
            - "@sylius.repository.shipping_method"
            - "@sylius.repository.shipment"
            - "@sylius.factory.address"
        tags:
            - { name: kernel.event_listener, event: sylius.order.pre_complete, method: addShippingAddress }

    app.form.extension.type.checkout_shipment:
        class: MagentixPickupPlugin\Form\Extension\CheckoutShipmentTypeExtension
        arguments:
            - "@sylius.registry.shipping_calculator"
            - "@sylius.repository.shipping_method"
            - "@translator.default"
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\ShipmentType }

    app.form.extension.type.shipping_method_choice:
        class: MagentixPickupPlugin\Form\Extension\ShippingMethodChoiceTypeExtension
        arguments:
            - "@sylius.registry.shipping_calculator"
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ShippingBundle\Form\Type\ShippingMethodChoiceType }

    sylius.customer_order_addresses_saver:
        class: MagentixPickupPlugin\Component\Core\Customer\CustomerOrderAddressesSaver
        public: true
        arguments:
            - "@sylius.customer_unique_address_adder"